; Chinese localization for NSIS installer options
; Copyright 2026 hesphoros
; Translated from InstallOptions.ini

[Settings]
NumFields=3

[Field 1]
Type=GroupBox
Text=设置位置
Left=0
Right=-1
Top=0
Bottom=39

[Field 2]
Flags=GROUP
Type=RadioButton
Text=%APPDATA%\voidImageViewer
State=1
Left=6
Right=-6
Top=10
Bottom=23

[Field 3]
Type=RadioButton
Text=安装文件夹
State=0
Left=6
Right=-6
Top=23
Bottom=36
