//
// Copyright 2026 hesphoros
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// Language/Localization support

#ifndef LANGUAGE_H
#define LANGUAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// Define utf8_t if not already defined (to avoid circular dependency with viv.h)
#ifndef utf8_t
typedef unsigned char utf8_t;
#endif

enum
{
	LANGUAGE_ENGLISH = 0,
	LANGUAGE_CHINESE_SIMPLIFIED = 1,
	LANGUAGE_COUNT
};

// Get localized string for a command name
// Returns UTF-8 encoded string
const utf8_t *language_get_string(int string_id);

// Get current language
int language_get_current(void);

// Set language (0 = English, 1 = Chinese Simplified)
void language_set(int lang);

// Initialize language system (detects system language)
void language_init(void);

// String IDs for menu items and UI text
enum
{
	// File menu
	LANG_STR_FILE = 0,
	LANG_STR_OPEN_FILE,
	LANG_STR_OPEN_FOLDER,
	LANG_STR_OPEN_EVERYTHING_SEARCH,
	LANG_STR_ADD_FILE,
	LANG_STR_ADD_FOLDER,
	LANG_STR_ADD_EVERYTHING_SEARCH,
	LANG_STR_OPEN_FILE_LOCATION,
	LANG_STR_EDIT,
	LANG_STR_PREVIEW,
	LANG_STR_PRINT,
	LANG_STR_SET_DESKTOP_WALLPAPER,
	LANG_STR_CLOSE,
	LANG_STR_DELETE,
	LANG_STR_DELETE_RECYCLE,
	LANG_STR_DELETE_PERMANENTLY,
	LANG_STR_RENAME,
	LANG_STR_PROPERTIES,
	LANG_STR_EXIT,
	
	// Edit menu
	LANG_STR_EDIT_MENU,
	LANG_STR_CUT,
	LANG_STR_COPY,
	LANG_STR_COPY_FILENAME,
	LANG_STR_COPY_IMAGE,
	LANG_STR_PASTE,
	LANG_STR_ROTATE_CLOCKWISE,
	LANG_STR_ROTATE_COUNTERCLOCKWISE,
	LANG_STR_COPY_TO,
	LANG_STR_MOVE_TO,
	
	// View menu
	LANG_STR_VIEW,
	LANG_STR_CAPTION,
	LANG_STR_FRAME,
	LANG_STR_MENU,
	LANG_STR_STATUS_BAR,
	LANG_STR_CONTROLS,
	LANG_STR_PRESET,
	LANG_STR_MINIMAL,
	LANG_STR_COMPACT,
	LANG_STR_NORMAL,
	LANG_STR_FULLSCREEN,
	LANG_STR_SLIDESHOW,
	LANG_STR_WINDOW_SIZE,
	LANG_STR_AUTO_FIT,
	LANG_STR_REFRESH,
	LANG_STR_ALLOW_SHRINKING,
	LANG_STR_KEEP_ASPECT_RATIO,
	LANG_STR_FILL_WINDOW,
	LANG_STR_BEST_FIT,
	LANG_STR_PAN_SCAN,
	LANG_STR_INCREASE_SIZE,
	LANG_STR_DECREASE_SIZE,
	LANG_STR_INCREASE_WIDTH,
	LANG_STR_DECREASE_WIDTH,
	LANG_STR_INCREASE_HEIGHT,
	LANG_STR_DECREASE_HEIGHT,
	LANG_STR_ZOOM,
	LANG_STR_ZOOM_IN,
	LANG_STR_ZOOM_OUT,
	LANG_STR_RESET,
	LANG_STR_MOVE_UP,
	LANG_STR_MOVE_DOWN,
	LANG_STR_MOVE_LEFT,
	LANG_STR_MOVE_RIGHT,
	LANG_STR_MOVE_UP_LEFT,
	LANG_STR_MOVE_UP_RIGHT,
	LANG_STR_MOVE_DOWN_LEFT,
	LANG_STR_MOVE_DOWN_RIGHT,
	LANG_STR_MOVE_CENTER,
	LANG_STR_ON_TOP,
	LANG_STR_ALWAYS,
	LANG_STR_WHILE_PLAYING_OR_ANIMATING,
	LANG_STR_NEVER,
	LANG_STR_OPTIONS,
	
	// Slideshow menu
	LANG_STR_SLIDESHOW_MENU,
	LANG_STR_PLAY_PAUSE,
	LANG_STR_RATE,
	LANG_STR_DECREASE_RATE,
	LANG_STR_INCREASE_RATE,
	LANG_STR_CUSTOM,
	
	// Animation menu
	LANG_STR_ANIMATION,
	LANG_STR_JUMP_FORWARD,
	LANG_STR_JUMP_BACKWARD,
	LANG_STR_SHORT_JUMP_FORWARD,
	LANG_STR_SHORT_JUMP_BACKWARD,
	LANG_STR_LONG_JUMP_FORWARD,
	LANG_STR_LONG_JUMP_BACKWARD,
	LANG_STR_FRAME_STEP,
	LANG_STR_PREVIOUS_FRAME,
	LANG_STR_FIRST_FRAME,
	LANG_STR_LAST_FRAME,
	LANG_STR_DECREASE_RATE_ANIM,
	LANG_STR_INCREASE_RATE_ANIM,
	LANG_STR_RESET_RATE,
	
	// Navigate menu
	LANG_STR_NAVIGATE,
	LANG_STR_NEXT,
	LANG_STR_PREVIOUS,
	LANG_STR_HOME,
	LANG_STR_END,
	LANG_STR_SORT,
	LANG_STR_NAME,
	LANG_STR_FULL_PATH,
	LANG_STR_SIZE,
	LANG_STR_DATE_MODIFIED,
	LANG_STR_DATE_CREATED,
	LANG_STR_ASCENDING,
	LANG_STR_DESCENDING,
	LANG_STR_SHUFFLE,
	LANG_STR_JUMP_TO,
	
	// Help menu
	LANG_STR_HELP,
	LANG_STR_HELP_MENU,
	LANG_STR_COMMAND_LINE_OPTIONS,
	LANG_STR_HOME_PAGE,
	LANG_STR_DONATE,
	LANG_STR_ABOUT,
	
	// Dialog strings
	LANG_STR_OPTIONS_TITLE,
	LANG_STR_GENERAL,
	LANG_STR_VIEW_DIALOG,
	LANG_STR_CONTROLS_DIALOG,
	LANG_STR_OK,
	LANG_STR_CANCEL,
	LANG_STR_STORE_SETTINGS_APPDATA,
	LANG_STR_ALLOW_MULTIPLE_INSTANCES,
	LANG_STR_STARTMENU_SHORTCUTS,
	LANG_STR_ASSOCIATIONS,
	LANG_STR_CHECK_ALL,
	LANG_STR_CHECK_NONE,
	LANG_STR_SHRINK_BLIT_MODE,
	LANG_STR_MAGNIFY_BLIT_MODE,
	LANG_STR_AUTO_SIZE_WINDOW,
	LANG_STR_PLAY_ANIMATIONS_ONCE,
	LANG_STR_PRELOAD_NEXT_IMAGE,
	LANG_STR_CACHE_LAST_IMAGE,
	LANG_STR_WINDOWED_BACKGROUND_COLOR,
	LANG_STR_FULLSCREEN_BACKGROUND_COLOR,
	LANG_STR_LEFT_CLICK_ACTION,
	LANG_STR_RIGHT_CLICK_ACTION,
	LANG_STR_MOUSE_WHEEL_ACTION,
	LANG_STR_COMMANDS,
	LANG_STR_SETTINGS_FOR_SELECTED_COMMAND,
	LANG_STR_ADD,
	LANG_STR_ADD_KEYBOARD_SHORTCUT,
	LANG_STR_EDIT_KEYBOARD_SHORTCUT,
	LANG_STR_SHORTCUT_KEY,
	LANG_STR_SHORTCUT_KEY_CURRENTLY_USED_BY,
	LANG_STR_REMOVE,
	LANG_STR_SET_CUSTOM_RATE,
	LANG_STR_CUSTOM_RATE,
	LANG_STR_ABOUT_TITLE,
	LANG_STR_RENAME_TITLE,
	LANG_STR_JUMP_TO_TITLE,
	LANG_STR_SEARCH_EVERYTHING,
	LANG_STR_RANDOMIZE,
	
	// Time units
	LANG_STR_MILLISECONDS,
	LANG_STR_SECONDS,
	LANG_STR_MINUTE,
	LANG_STR_MINUTES,
	
	// Application name
	LANG_STR_APP_NAME,
	
	LANG_STR_COUNT
};

#ifdef __cplusplus
}
#endif

#endif // LANGUAGE_H
