//
// Copyright 2026 hesphoros
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// Language/Localization support

#ifndef LANGUAGE_H
#define LANGUAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// Define utf8_t if not already defined (to avoid circular dependency with viv.h)
#ifndef utf8_t
typedef unsigned char utf8_t;
#endif

enum
{
	LOCALIZATION_LANGUAGE_ENGLISH = 0,
	LOCALIZATION_LANGUAGE_CHINESE_SIMPLIFIED,
	LOCALIZATION_LANGUAGE_COUNT,
};

typedef BYTE localization_id_t;

#define LOCALIZATION_ID_INVALID 255

// Get localized string for a command name
// Returns UTF-8 encoded string
const utf8_t *localization_get_string(localization_id_t localization_id);

// Get current language
int language_get_current(void);

// Set language (0 = English, 1 = Chinese Simplified)
void language_set(int lang);

// Initialize language system (detects system language)
void localization_init(void);

// String IDs for menu items and UI text
enum
{
	// Localization
	LOCALIZATION_ID_LANGUAGE = 0,

	// Application name
	LOCALIZATION_ID_APP_NAME,
	
	// File menu
	LOCALIZATION_ID_FILE,
	LOCALIZATION_ID_OPEN_FILE,
	LOCALIZATION_ID_OPEN_FOLDER,
	LOCALIZATION_ID_OPEN_EVERYTHING_SEARCH,
	LOCALIZATION_ID_ADD_FILE,
	LOCALIZATION_ID_ADD_FOLDER,
	LOCALIZATION_ID_ADD_EVERYTHING_SEARCH,
	LOCALIZATION_ID_OPEN_FILE_LOCATION,
	LOCALIZATION_ID_EDIT,
	LOCALIZATION_ID_PREVIEW,
	LOCALIZATION_ID_PRINT,
	LOCALIZATION_ID_SET_DESKTOP_WALLPAPER,
	LOCALIZATION_ID_CLOSE,
	LOCALIZATION_ID_DELETE,
	LOCALIZATION_ID_DELETE_RECYCLE,
	LOCALIZATION_ID_DELETE_PERMANENTLY,
	LOCALIZATION_ID_RENAME,
	LOCALIZATION_ID_PROPERTIES,
	LOCALIZATION_ID_EXIT,
	
	// Edit menu
	LOCALIZATION_ID_EDIT_MENU,
	LOCALIZATION_ID_CUT,
	LOCALIZATION_ID_COPY,
	LOCALIZATION_ID_COPY_FILENAME,
	LOCALIZATION_ID_COPY_IMAGE,
	LOCALIZATION_ID_PASTE,
	LOCALIZATION_ID_ROTATE_CLOCKWISE,
	LOCALIZATION_ID_ROTATE_COUNTERCLOCKWISE,
	LOCALIZATION_ID_COPY_TO,
	LOCALIZATION_ID_MOVE_TO,
	
	// View menu
	LOCALIZATION_ID_VIEW,
	LOCALIZATION_ID_CAPTION,
	LOCALIZATION_ID_FRAME,
	LOCALIZATION_ID_MENU,
	LOCALIZATION_ID_STATUS_BAR,
	LOCALIZATION_ID_CONTROLS,
	LOCALIZATION_ID_PRESET,
	LOCALIZATION_ID_MINIMAL,
	LOCALIZATION_ID_COMPACT,
	LOCALIZATION_ID_NORMAL,
	LOCALIZATION_ID_FULLSCREEN,
	LOCALIZATION_ID_SLIDESHOW,
	LOCALIZATION_ID_WINDOW_SIZE,
	LOCALIZATION_ID_AUTO_FIT,
	LOCALIZATION_ID_REFRESH,
	LOCALIZATION_ID_ALLOW_SHRINKING,
	LOCALIZATION_ID_KEEP_ASPECT_RATIO,
	LOCALIZATION_ID_FILL_WINDOW,
	LOCALIZATION_ID_BEST_FIT,
	LOCALIZATION_ID_PAN_SCAN,
	LOCALIZATION_ID_INCREASE_SIZE,
	LOCALIZATION_ID_DECREASE_SIZE,
	LOCALIZATION_ID_INCREASE_WIDTH,
	LOCALIZATION_ID_DECREASE_WIDTH,
	LOCALIZATION_ID_INCREASE_HEIGHT,
	LOCALIZATION_ID_DECREASE_HEIGHT,
	LOCALIZATION_ID_ZOOM,
	LOCALIZATION_ID_ZOOM_IN,
	LOCALIZATION_ID_ZOOM_OUT,
	LOCALIZATION_ID_RESET,
	LOCALIZATION_ID_MOVE_UP,
	LOCALIZATION_ID_MOVE_DOWN,
	LOCALIZATION_ID_MOVE_LEFT,
	LOCALIZATION_ID_MOVE_RIGHT,
	LOCALIZATION_ID_MOVE_UP_LEFT,
	LOCALIZATION_ID_MOVE_UP_RIGHT,
	LOCALIZATION_ID_MOVE_DOWN_LEFT,
	LOCALIZATION_ID_MOVE_DOWN_RIGHT,
	LOCALIZATION_ID_MOVE_CENTER,
	LOCALIZATION_ID_ON_TOP,
	LOCALIZATION_ID_ALWAYS,
	LOCALIZATION_ID_WHILE_PLAYING_OR_ANIMATING,
	LOCALIZATION_ID_NEVER,
	LOCALIZATION_ID_OPTIONS,
	
	// Slideshow menu
	LOCALIZATION_ID_SLIDESHOW_MENU,
	LOCALIZATION_ID_PLAY_PAUSE,
	LOCALIZATION_ID_RATE,
	LOCALIZATION_ID_DECREASE_RATE,
	LOCALIZATION_ID_INCREASE_RATE,
	LOCALIZATION_ID_CUSTOM,
	
	// Animation menu
	LOCALIZATION_ID_ANIMATION,
	LOCALIZATION_ID_JUMP_FORWARD,
	LOCALIZATION_ID_JUMP_BACKWARD,
	LOCALIZATION_ID_SHORT_JUMP_FORWARD,
	LOCALIZATION_ID_SHORT_JUMP_BACKWARD,
	LOCALIZATION_ID_LONG_JUMP_FORWARD,
	LOCALIZATION_ID_LONG_JUMP_BACKWARD,
	LOCALIZATION_ID_FRAME_STEP,
	LOCALIZATION_ID_PREVIOUS_FRAME,
	LOCALIZATION_ID_FIRST_FRAME,
	LOCALIZATION_ID_LAST_FRAME,
	LOCALIZATION_ID_DECREASE_RATE_ANIM,
	LOCALIZATION_ID_INCREASE_RATE_ANIM,
	LOCALIZATION_ID_RESET_RATE,
	
	// Navigate menu
	LOCALIZATION_ID_NAVIGATE,
	LOCALIZATION_ID_NEXT,
	LOCALIZATION_ID_PREVIOUS,
	LOCALIZATION_ID_HOME,
	LOCALIZATION_ID_END,
	LOCALIZATION_ID_SORT,
	LOCALIZATION_ID_NAME,
	LOCALIZATION_ID_FULL_PATH,
	LOCALIZATION_ID_SIZE,
	LOCALIZATION_ID_DATE_MODIFIED,
	LOCALIZATION_ID_DATE_CREATED,
	LOCALIZATION_ID_ASCENDING,
	LOCALIZATION_ID_DESCENDING,
	LOCALIZATION_ID_SHUFFLE,
	LOCALIZATION_ID_JUMP_TO,
	
	// Help menu
	LOCALIZATION_ID_HELP,
	LOCALIZATION_ID_HELP_MENU,
	LOCALIZATION_ID_COMMAND_LINE_OPTIONS,
	LOCALIZATION_ID_HOME_PAGE,
	LOCALIZATION_ID_DONATE,
	LOCALIZATION_ID_ABOUT,
	LOCALIZATION_ID_HELP_SUPPORT_URL,
	LOCALIZATION_ID_HELP_DONATE_URL,
	LOCALIZATION_ID_HELP_WEBSITE_URL,
	
	// Dialog strings
	LOCALIZATION_ID_OPTIONS_TITLE,
	LOCALIZATION_ID_GENERAL,
	LOCALIZATION_ID_VIEW_DIALOG,
	LOCALIZATION_ID_CONTROLS_DIALOG,
	LOCALIZATION_ID_OK,
	LOCALIZATION_ID_CANCEL,
	LOCALIZATION_ID_STORE_SETTINGS_APPDATA,
	LOCALIZATION_ID_ALLOW_MULTIPLE_INSTANCES,
	LOCALIZATION_ID_STARTMENU_SHORTCUTS,
	LOCALIZATION_ID_ASSOCIATIONS,
	LOCALIZATION_ID_CHECK_ALL,
	LOCALIZATION_ID_CHECK_NONE,
	LOCALIZATION_ID_SHRINK_BLIT_MODE,
	LOCALIZATION_ID_MAGNIFY_BLIT_MODE,
	LOCALIZATION_ID_AUTO_SIZE_WINDOW,
	LOCALIZATION_ID_PLAY_ANIMATIONS_ONCE,
	LOCALIZATION_ID_PRELOAD_NEXT_IMAGE,
	LOCALIZATION_ID_CACHE_LAST_IMAGE,
	LOCALIZATION_ID_WINDOWED_BACKGROUND_COLOR,
	LOCALIZATION_ID_FULLSCREEN_BACKGROUND_COLOR,
	LOCALIZATION_ID_LEFT_CLICK_ACTION,
	LOCALIZATION_ID_RIGHT_CLICK_ACTION,
	LOCALIZATION_ID_MOUSE_WHEEL_ACTION,
	LOCALIZATION_ID_COMMANDS,
	LOCALIZATION_ID_SETTINGS_FOR_SELECTED_COMMAND,
	LOCALIZATION_ID_ADD,
	LOCALIZATION_ID_ADD_KEYBOARD_SHORTCUT,
	LOCALIZATION_ID_EDIT_KEYBOARD_SHORTCUT,
	LOCALIZATION_ID_SHORTCUT_KEY,
	LOCALIZATION_ID_SHORTCUT_KEY_CURRENTLY_USED_BY,
	LOCALIZATION_ID_REMOVE,
	LOCALIZATION_ID_SET_CUSTOM_RATE,
	LOCALIZATION_ID_CUSTOM_RATE,
	LOCALIZATION_ID_ABOUT_TITLE,
	LOCALIZATION_ID_RENAME_TITLE,
	LOCALIZATION_ID_JUMP_TO_TITLE,
	LOCALIZATION_ID_SEARCH_EVERYTHING,
	LOCALIZATION_ID_RANDOMIZE,
	
	// Time units
	LOCALIZATION_ID_MILLISECONDS,
	LOCALIZATION_ID_SECONDS,
	LOCALIZATION_ID_MINUTE,
	LOCALIZATION_ID_MINUTES,
	
	LOCALIZATION_ID_COUNT
};

extern BYTE localization_language;

#ifdef __cplusplus
}
#endif

#endif // LANGUAGE_H
